# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Alamofire', '3.3.1'
pod 'Kingfisher', '2.2.2'

target 'UnsplashItGallery' do

end

