# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Kingfisher'
pod 'DGElasticPullToRefresh'
pod 'ReachabilitySwift', '~> 3'
pod 'Alamofire'
pod 'HandyJSON'

target 'UnsplashItGallery' do

end
